CREATE SCHEMA IF NOT EXISTS users AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS lodges AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS reservations AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS payments AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS coupons AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS notifications AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS reviews AUTHORIZATION postgres;
